variants="/bp1/mrcieu1/data/encode/public/cosmicGnomad_20230215/cosmicGnomadVariants.bed"
featureOutputDir="/bp1/mrcieu1/data/encode/public/cosmicGnomad_20230215/features/"
dinucleotidePropertyTable="/bp1/mrcieu1/data/encode/public/cosmicGnomad_20230215/dinucleotidePropertyTable.csv"
vepConsequenceOutput="/bp1/mrcieu1/data/encode/public/cosmicGnomad_20230215/features/variant_effect_output_conseq.txt"
vepAAOutput="/bp1/mrcieu1/data/encode/public/cosmicGnomad_20230215/features/variant_effect_output_AA.txt"
vepDistanceOutput="/bp1/mrcieu1/data/encode/public/cosmicGnomad_20230215/features/variant_effect_output_distance.txt"
featureScriptDir="/bp1/mrcieu1/users/uw20204/paper1/features/"
